apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
  namespace: monitoring-apps
  labels:
    app: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      containers:
        - name: loadgen
          image: monitoring/loadgen:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: LOADGEN_TARGET_URL
              value: "http://actuator:8081"
          ports:
            - name: http
              containerPort: 8082
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
